### ISSUE TITLE
Levels won't open.

### ISSUE THREAD

**Issue by mesmerneru** [crewly/comboBurst#5] opened 2024-06-16 16:33 UTC
Hey there, I am running Combo Burst 1.1.0 on Geode 3.0.0 and I noticed that when I have the mod on, the levels won't really open. I tried pasting the old files into the resources folder but they don't work as well. I really like this mod and I really want to use it again.

**Comment by mesmerneru** [comment] 2024-06-16 16:38
1.1.0-beta 2*

**Comment by crewly** [comment] 2024-06-17 16:20
Hello, can you specify the OS platform you're playing on and send any crash reports (if there are any) related to this issue? Cheers

**Comment by TrapSupremacy** [comment] 2024-06-18 00:50
I have almost the same issue, I'm on windows 10 with geode v3.0.0-beta.1 and Comboburst v1.1.0-beta.2 and my game crash when I try to play a level, they don't give me crash report when it crashes sadly
Kinda sad cause ur mod looked fun :(

**Comment by crewly** [comment] 2024-06-18 09:19
@TrapSupremacy have you tried [previous versions of comboburst](https://github.com/crewly/comboBurst/releases)? (e.g. v1.1.0-beta.1, alpha releases, etc.). Do the crashes only happen on beta.2?

**Comment by TrapSupremacy** [comment] 2024-06-18 16:04
I just tried, beta 1 and 2 don't work but alpha 2 work fine, hope my small feedback help :)

**Comment by TrapSupremacy** [comment] 2024-06-18 17:32
I found my issue it's was texture loader (I use blueskii texture pack and idk if the problem is texture loader itself or blueskii TP) I just deactivate it and comboburst work in beta.2, sry for the inconvenience I should've thought about that tbh

**Comment by crewly** [comment] 2024-06-19 06:59
The problem appears to be a mod incompatibility with the Texture Loader mod. Looking into it.

**Comment by crewly** [comment] 2024-06-20 16:57
This issue should be fixed in the new beta version of Geode

**Closed as completed by crewly** 2024-06-20 16:57 UTC
